export const SALES_FETCHED = 'SALES_FETCHED';
export const SALES_FETCHED_SUCCEDDED = 'SALES_FETCHED_SUCCEDDED';
export const SALES_FETCHED_FAILED = 'SALES_FETCHED_FAILED';

export const SALES_FORECAST_FETCHED = 'SALES_FORECAST_FETCHED';
export const SALES_FORECAST_FETCHED_SUCCEDDED = 'SALES_FORECAST_FETCHED_SUCCEDDED';
export const SALES_FORECAST_FETCHED_FAILED = 'SALES_FORECAST_FETCHED_FAILED';